### ISSUE TITLE
Trying to contact you.

### ISSUE THREAD

**Issue by sazo** [Yacodo/ygg-db#1]
Hallo @Yacodo,

I am trying to get in touch with you. But i am not sure if you email on your github account is up-to-date, so maybe using the issue system will help me. :)

Its about `yggdrasil` vendor name on packagist and we(me and my company) are interested in it. 

Looking forward to hearing from you.

**Comment by Yacodo** [comment]
Hello,

Sorry for the delay, I'm getting back to you in few minutes by email ;)
